# Minimal codecov configuration
coverage:
  status:
    project:
      default:
        target: 80  # Automatically set coverage target
        threshold: 5% # Allow 5% drop in coverage

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false